# Dependabot configuration for automated dependency updates
# See https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Backend npm dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Kunj-Sharma03"
    assignees:
      - "Kunj-Sharma03"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "apollo-server-express"
        update-types: ["version-update:semver-major"]

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Kunj-Sharma03"
    assignees:
      - "Kunj-Sharma03"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Ignore major version updates for React and Next.js
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "Kunj-Sharma03"
    assignees:
      - "Kunj-Sharma03"
    commit-message:
      prefix: "🔄"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
    reviewers:
      - "Kunj-Sharma03"
    assignees:
      - "Kunj-Sharma03"
    commit-message:
      prefix: "🐳"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    reviewers:
      - "Kunj-Sharma03"
    assignees:
      - "Kunj-Sharma03"
    commit-message:
      prefix: "🐳"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
