[phases.setup]
nixpkgs = ["nodejs_20"]

[phases.install]
cmds = [
	"if [ -f package-lock.json ]; then npm ci --omit=dev; else npm install --omit=dev; fi"
]

[phases.build]
cmds = []

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
